import type { CandidateCardData, JobCardData, SwipeCardData } from '../../types';

/**
 * Static deck data for DEMO-09.
 *
 * The swipe deck ticket is explicitly buildable before the backend exists, so this stands in for
 * `GET /discover/jobs` and `GET /discover/candidates` until DEMO-08 lands. It is **not** the seed
 * data for the client demo — that's DEMO-17, generated server-side against the real database.
 *
 * Scores are deliberately spread from the 30s to the low 90s. Demo PRD §4 is blunt about why: a
 * deck where every card reads 90%+ looks fabricated, and the whole point of showing a match score
 * is that it discriminates between cards.
 */

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const MOCK_JOBS: JobCardData[] = [
  {
    id: 'job-1',
    title: 'Senior Backend Engineer',
    companyName: 'Razorpay',
    companyLogoUrl: null,
    locationCity: 'Bengaluru',
    workMode: 'remote',
    compMin: 1_800_000,
    compMax: 2_800_000,
    experienceMinYears: 3,
    experienceMaxYears: 5,
    techStack: ['Node.js', 'TypeScript', 'AWS', 'Postgres', 'Kafka', 'Redis'],
    description:
      "Own the payments infra team's core ledger service, processing 40M transactions a day. You'll lead the migration off the legacy settlement pipeline.",
    postedAt: daysAgo(2),
    matchScore: 91,
    matchedSkills: ['Node.js', 'TypeScript', 'AWS', 'Postgres'],
  },
  {
    id: 'job-2',
    title: 'Platform Engineer',
    companyName: 'Zerodha',
    companyLogoUrl: null,
    locationCity: 'Bengaluru',
    workMode: 'onsite',
    compMin: 2_200_000,
    compMax: 3_200_000,
    experienceMinYears: 4,
    experienceMaxYears: 7,
    techStack: ['Go', 'Kubernetes', 'Postgres', 'Redis', 'Terraform'],
    description:
      'Build and run the trading platform that clears a fifth of all Indian retail equity volume. Low latency matters here more than anywhere else you have worked.',
    postedAt: daysAgo(1),
    matchScore: 74,
    matchedSkills: ['Postgres', 'Redis'],
  },
  {
    id: 'job-3',
    title: 'Full Stack Engineer',
    companyName: 'CRED',
    companyLogoUrl: null,
    locationCity: 'Bengaluru',
    workMode: 'hybrid',
    compMin: 1_600_000,
    compMax: 2_400_000,
    experienceMinYears: 2,
    experienceMaxYears: 4,
    techStack: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    description:
      'Ship member-facing features end to end on a product where the design bar is the point. Small teams, direct ownership, weekly releases.',
    postedAt: daysAgo(4),
    matchScore: 83,
    matchedSkills: ['React', 'TypeScript', 'Node.js'],
  },
  {
    id: 'job-4',
    title: 'Data Engineer',
    companyName: 'Swiggy',
    companyLogoUrl: null,
    locationCity: 'Bengaluru',
    workMode: 'hybrid',
    compMin: 1_400_000,
    compMax: 2_200_000,
    experienceMinYears: 3,
    experienceMaxYears: 6,
    techStack: ['Python', 'Spark', 'Airflow', 'SQL', 'AWS'],
    description:
      'Own the demand-forecasting pipelines behind delivery-time estimates. Terabyte-scale batch plus a streaming path that cannot fall behind.',
    postedAt: daysAgo(6),
    matchScore: 58,
    matchedSkills: ['SQL', 'AWS'],
  },
  {
    id: 'job-5',
    title: 'Backend Engineer, API Platform',
    companyName: 'Postman',
    companyLogoUrl: null,
    locationCity: 'Bengaluru',
    workMode: 'remote',
    compMin: 2_000_000,
    compMax: 3_000_000,
    experienceMinYears: 4,
    experienceMaxYears: 8,
    techStack: ['Node.js', 'TypeScript', 'Postgres', 'Docker', 'gRPC'],
    description:
      'Work on the collection-sync engine used by 30 million developers. Correctness under concurrent edits is the hard part, and the interesting one.',
    postedAt: daysAgo(3),
    matchScore: 88,
    matchedSkills: ['Node.js', 'TypeScript', 'Postgres', 'Docker'],
  },
  {
    id: 'job-6',
    title: 'Mobile Engineer (React Native)',
    companyName: 'Groww',
    companyLogoUrl: null,
    locationCity: 'Bengaluru',
    workMode: 'hybrid',
    compMin: 1_500_000,
    compMax: 2_300_000,
    experienceMinYears: 2,
    experienceMaxYears: 5,
    techStack: ['React Native', 'TypeScript', 'Reanimated', 'iOS', 'Android'],
    description:
      'Own the investing flows in an app 10 million people check before market open. Performance work here is measured in dropped frames, not page loads.',
    postedAt: daysAgo(1),
    matchScore: 67,
    matchedSkills: ['TypeScript', 'React Native'],
  },
  {
    id: 'job-7',
    title: 'Site Reliability Engineer',
    companyName: 'Freshworks',
    companyLogoUrl: null,
    locationCity: 'Chennai',
    workMode: 'onsite',
    compMin: 1_700_000,
    compMax: 2_600_000,
    experienceMinYears: 5,
    experienceMaxYears: 9,
    techStack: ['Kubernetes', 'Terraform', 'Go', 'Prometheus', 'AWS'],
    description:
      'Run the multi-region control plane behind a suite serving 60,000 businesses. On-call is real, and so is the headroom to fix what wakes you up.',
    postedAt: daysAgo(9),
    matchScore: 42,
    matchedSkills: ['AWS'],
  },
  {
    id: 'job-8',
    title: 'Engineering Manager, Payments',
    companyName: 'Zoho',
    companyLogoUrl: null,
    locationCity: 'Chennai',
    workMode: 'onsite',
    compMin: null,
    compMax: null,
    experienceMinYears: 8,
    experienceMaxYears: null,
    techStack: ['Java', 'Postgres', 'Kafka', 'System Design'],
    description:
      'Lead a team of nine across two payment products. Hands-on enough to review a schema change, senior enough to own the roadmap.',
    postedAt: daysAgo(12),
    matchScore: 35,
    matchedSkills: ['Postgres'],
  },
];

export const MOCK_CANDIDATES: CandidateCardData[] = [
  {
    id: 'cand-1',
    firstName: 'Aditi',
    lastInitial: 'K',
    currentTitle: 'Senior Backend Engineer',
    yearsExperience: 5,
    locationCity: 'Bengaluru',
    preferredWorkMode: 'remote',
    skills: ['Node.js', 'Postgres', 'AWS', 'System Design', 'TypeScript', 'Redis'],
    matchedSkills: ['Node.js', 'Postgres', 'AWS', 'TypeScript'],
    keyAchievement: 'Led migration cutting infra cost 30%',
    hasResume: true,
    matchScore: 92,
  },
  {
    id: 'cand-2',
    firstName: 'Rohan',
    lastInitial: 'M',
    currentTitle: 'Backend Engineer',
    yearsExperience: 3,
    locationCity: 'Pune',
    preferredWorkMode: 'hybrid',
    skills: ['Node.js', 'TypeScript', 'MongoDB', 'Docker'],
    matchedSkills: ['Node.js', 'TypeScript', 'Docker'],
    keyAchievement: 'Cut p99 checkout latency from 1.4s to 320ms',
    hasResume: true,
    matchScore: 79,
  },
  {
    id: 'cand-3',
    firstName: 'Meera',
    lastInitial: 'S',
    currentTitle: 'Platform Engineer',
    yearsExperience: 6,
    locationCity: 'Hyderabad',
    preferredWorkMode: 'remote',
    skills: ['Go', 'Kubernetes', 'Terraform', 'Postgres', 'AWS'],
    matchedSkills: ['Postgres', 'AWS'],
    keyAchievement: 'Ran a zero-downtime move across two AWS regions',
    hasResume: true,
    matchScore: 64,
  },
  {
    id: 'cand-4',
    firstName: 'Karthik',
    lastInitial: 'R',
    currentTitle: 'Full Stack Engineer',
    yearsExperience: 4,
    locationCity: 'Chennai',
    preferredWorkMode: 'onsite',
    skills: ['React', 'Node.js', 'GraphQL', 'Postgres', 'TypeScript'],
    matchedSkills: ['Node.js', 'Postgres', 'TypeScript'],
    keyAchievement: 'Rebuilt the seller dashboard used by 40k merchants',
    hasResume: true,
    matchScore: 81,
  },
  {
    id: 'cand-5',
    firstName: 'Ananya',
    lastInitial: 'B',
    currentTitle: 'Data Engineer',
    yearsExperience: 2,
    locationCity: 'Bengaluru',
    preferredWorkMode: 'hybrid',
    skills: ['Python', 'Airflow', 'SQL', 'Spark'],
    matchedSkills: ['SQL'],
    keyAchievement: 'Built the churn model now used in weekly planning',
    hasResume: true,
    matchScore: 46,
  },
  {
    id: 'cand-6',
    firstName: 'Devansh',
    lastInitial: 'P',
    currentTitle: 'Mobile Engineer',
    yearsExperience: 7,
    locationCity: 'Mumbai',
    preferredWorkMode: 'remote',
    skills: ['React Native', 'TypeScript', 'Reanimated', 'iOS', 'Android', 'Node.js'],
    matchedSkills: ['TypeScript', 'Node.js'],
    keyAchievement: 'Took a 42-screen app from 38fps to a locked 60fps',
    hasResume: false,
    matchScore: 57,
  },
];

export const MOCK_JOB_DECK: SwipeCardData[] = MOCK_JOBS.map((data) => ({ kind: 'job', data }));

export const MOCK_CANDIDATE_DECK: SwipeCardData[] = MOCK_CANDIDATES.map((data) => ({
  kind: 'candidate',
  data,
}));
